<TestButton>:
    button_label: button_label

    BoxLayout:



        orientation: "vertical"
        Label:
            text: "Game"
            font_size: 64
            color: 0.5, 0.5, 0.5, 1
        Label:
            text: "-"
            font_size: 64
        Button:
            id: button_label
            text: "Press me!"
            font_size: 32
            size: 100, 50
            on_press: root.pressed()
